#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#spec:
#  selector:
#    app: postgres
#  ports:
#    - port: 5432
#      targetPort: 5432

apiVersion: v1
kind: Service
metadata:
  name: lilvegas-service
spec:
  type: NodePort
  selector:
    app: lilvegas
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001  # או כל פורט אחר בין 30000–32767

